### ISSUE TITLE
Patched filesystems

### ISSUE THREAD

**Issue by Eusebius1920** [szwacz/fs-jetpack#13]
I would like to hand in a feature request:

Make the used fs-module an (optional) option.

Reason:
In electron the original filesystem (require('fs')) is patched to support asar files (a zip-like format that allows random access) out of the box such that you can treat *.asar files as directories. 
Often this is very handy but unfortunately this causes problems with using fs-jetpack together with asar-files (for example copying is no longer possible). In electron there is a module called 'original-fs' that returns an unpatched version of the filesystem-module.

something like

```
fs = require('fs-jetpack')
fs.OPERATION( args, {fs: 'the used fs module'}
```

would be very handy.

What are you thinking of the idea?

**Comment by szwacz** [comment]
Hmmm, interesting idea. Give me some time to gather more knowledge on the topic and I'll get back to you then.

**Comment by szwacz** [comment]
It's working. Electron by default forces all modules to use its (patched) version of fs module which can read asar internals. No need for fs-jetpack to do something in order to support it.

One thing which might gone wrong in your case is that packaged electron app sets CWD to root directory (at least on osx). I did this in electron and it worked:

```js
var app = require('remote').require('app');
var jetpack = require('fs-jetpack').cwd(app.getAppPath());
console.log(jetpack.read('package.json', 'json'));
```

**Comment by Eusebius1920** [comment]
Yes, that is a really nice feature of electron, that you can use the asar like they were folders (This is really cool, if you are planning to release on windows, where you might get into problems with to long nested node_modules paths...)

But imagine the following:
You want to write an update-module for your electron app. It checks if there is a new version for your app and if so, it downloads the new asar file to some tmp directory. It does some integrity checks (md5 and such stuff) and then copies the asar to the user-data folder. This is not possible with the patched fs-module (at least not together with the great fs-jetpack, that lifts the low level node-fs module to an awesome high level).

I attached a minimal-example.
Usage:
```
npm install
npm start
````
(I stole some code for the startup task from your electron-boilerplate project to get it up and running quickly. That boilerplate project is also really awesome btw)

Minimal example: [electron-minimal.zip](https://www.dschlosser.de/files/electron-minimal.zip).

**Comment by szwacz** [comment]
Ok, now I get it. I understood you the other way around. Now it sounds reasonable.

**Comment by szwacz** [comment]
I did small proof of concept and this turned out to be much more code-complicating than I thought (also libraries `rimraf` and `mkdirp` must be ported directly to this codebase, so the fs switch can happen there as well).
But the idea is very nice, and could be used also for mocking original fs for testing purposes.
I'm not abandoning it yet, but for sure won't have time in incoming weeks to work on it.

**Comment by Eusebius1920** [comment]
Thank you, for your efforts!

At least in the case of `rimraf` there exists already a unmerged pull request with exactly the same intent:
https://github.com/isaacs/rimraf/pull/83

I will create an issue or pr for `mkdirp` as well, if I finde some free time the next weeks.

**Comment by Eusebius1920** [comment]
In the case of Electron this is resolved:
https://github.com/atom/electron/pull/3641

**Comment by szwacz** [comment]
If this wasn't implemented till now, probably never will be. Closing.

**Comment by Eusebius1920** [comment]
Reasonable!
