### ISSUE TITLE
minimatch

### ISSUE THREAD

**Issue by gbaumgart** [szwacz/fs-jetpack#30]
Hi,
not an issue but could you update to micromatch sometime? Minimatch is pretty outdated and lacks of important features compared. 
g

**Comment by szwacz** [comment]
Surely I can think of it. Lack of exactly which feature in minimatch made you file this issue?

**Comment by gbaumgart** [comment]
hi,
see https://www.npmjs.com/package/micromatch#features. i am missing speed and logical operators as well proper tests.

the bigger difference when replacing is the need for setting a root path and then adding it back to the results.

thanks a lot.

**Comment by gbaumgart** [comment]
well, and the documentation is shiny, at least compared ;-)

**Comment by szwacz** [comment]
I looked into micromatch and decided to stay with minimatch.
- Micromatch is much bigger dependency.
- Micromatch feature-richness can't be utilized in this project.
- In case of performance for fs-jetpack it doesn't offer real difference because the bottleneck here is hard disk I/O.
- I resolved the problem with micromatch docs by improving docs about matching options in fs-jetpack readme.

Still your proposition made this project better. Thanks! :)
