### ISSUE TITLE
move/delete/copy progress

### ISSUE THREAD

**Issue by xblox** [szwacz/fs-jetpack#39]
for some reasons fs-jetpack file operations seem pretty slow compared to its native counterparts, especially when it comes to large files or large directories. 

Might it be possible that you introduce some event with statistics about the progress ? If not, no problem. I was thinking to rewrite fs-jetpack in Typescript and add it myself. 

Regarding slowness, I wrote a [something](http://stackoverflow.com/questions/34142211/fast-file-copy-with-progress-information-in-node-js) on SO but appearently nobody has a workable solution. I was even considering to introduce 'shelljs' as alternative low-level implementation (uses the system's cp I think).

greets

**Comment by szwacz** [comment]
I know jetpack is slower than native, but so far always spent my time on api improvements and never addressed this issue (actually was waiting until someone will point that out to make me motivated ;).

Could you please provide some benchmarking how long the operation takes native and via jetpack on your machine and what type of files and folder structure are you copying?

Progress events is also something I was thinking about. This is not trivial to add, because:
- Copying algorithm doesn't perform any "let's count how much files there is to copy" task. It just starts traversing the folder tree and copying until it reaches the end of tree.
- Remove task uses `rimraf` module, so to add progress first in-house implementation need to be written as replacement for `rimraf`.
- Move? Isn't it just changeing one link in the file system and the operation is always more or less instantaneus?

I'll think what can be done in this matter. Of course all ideas are welcome.

**Comment by xblox** [comment]
I don't mind too much about speed, for now. I know it's rather a Javascript issue in itself (same reason it can't play properly audio on its own due to buffer issues). 

Let's stick to the event feature for now please. I am doing lots of file based tools (like mc or entire IDEs) and I always wanted to have progress for the mentioned operations because it brings my tools to a next level, at least compared to native file-managers (mc, total commander). The reason why I mentioned speed is because, a user might do file operations on larger amounts and currently I can't present him what's going on, nor any indication/estimate for how long. I know by heart how useful it is to have proper progress information when I maintain servers.

So yes, that's the motivation behind for me. Delivering native like quality. There is currently not a single Node.JS based tools/library delivering this kind of detail/quality. I'd like to get over it. I also don't need too much detail, but at least something....

However, its actually 2 problems 

1. progress events, and its implementation in fs-jetpack
2. counting file sizes and amounts (can be pretty slow, there is "du" on linux doing the best job but no similar variant for Windows)

For the former I am up to your suggestions or hints how you'd adjust fs-jetpack.

And for the counting sizes I can be of help, I was studying lots of linux source code (midnight commander), also the code for "cp". I can imagine to put this into some pseudo code and go from there. 

And for "move", yes & no, depends where the files go, if its another fs partition/disc then its same slow as copy.

If you want to get active on this, let me know. I can delegate time for the sizes problem as said.

Thanks a million, 
g

**Comment by xblox** [comment]
never mind. i will try my luck with a [Typescript port](https://github.com/xblox/fs-jetpack) of fs-jetpack.

**Comment by xblox** [comment]
mas o menos I have got it [done](https://github.com/xblox/fs-jetpack/blob/master/src/interfaces.ts#L60). Do you have by chance there any other wild ideas for jet-pack ? Btw. I am decoupling my fork as stand-alone to xblox/fs sometime soon.
anyways, thanks for your time again.
g

**Comment by xblox** [comment]
Hi,

about "move is the same as rename" again: no it's not. If the target is another device, fs-jetpack would throw an error "EXDEV". I fixed this in my version : https://github.com/xblox/fs/blob/master/src/move.ts#L27 

About progress and user side conflict/error handling again, I think I got it near perfect (for me) : http://rawgit.com/xblox/fs/master/docs/interfaces/_interfaces_.icopyoptions.html.

g
