### ISSUE TITLE
Consider dropping Node v0.x support

### ISSUE THREAD

**Issue by citycide** [szwacz/fs-jetpack#41]
Node v0.10 is a test target but has no further support from the Node org. Would you consider dropping it in the interest of using features supported in Node v4+?

Another thing tied into the above is the usage of Q for Promises. More spec compliant would be native Promises in Node v4+ or for performance ( and handy things like error handling & long stack traces ) there is also bluebird.

Would you accept PRs working on these?

**Comment by xblox** [comment]
@citycide, there is a Typescript port (https://github.com/xblox/fs-jetpack/tree/ts-initial). The 'initial' branch is just a port but I got rid of Q as much I could (stuck with Promise compliance in test units). However, my master branch will be about adding new features (progress, user conflict resolver for cp/mv and possibly alternate impl. for cp/move), not sure Jakub would consider picking it up some day.

**Comment by szwacz** [comment]
@citycide I have "dropping support for nodes 0.x" next on my todo list, so well timed :) I planned to use native promises, because I want fs-jetpack to have as little dependencies as possible. The only problem is that I'm using Q's `denodify`, but that feature seems to be one simple helper function, easy to be implemented in-house. If you want to contribute please do! I surely can leave it to you.

Do you mean any special features of node v4+? Regarding ES6 syntax I want to introduce it into codebase on my own. Right now the codebase is still linted for airbnb/legacy (ES5) and if you would like to submit a PR please keep that code style.

**Comment by szwacz** [comment]
@citycide for sure my project will stay in pure-js and it's general purpose file system library, so I don't want to go too deep into very special use cases. I'm certainly interested in exchangeing know-how and will be keeping an eye on your solutions.

**Comment by citycide** [comment]
@szwacz all noted. Happy to hear you want to go with native promises, I think that's a good choice. And `denodeify` is definitely not a blocker. Like you said it's an easy helper function.

For this codebase I think it would be mostly niceties when using ES2015 but considering the only node versions that don't support it are basically dead and gone the time's coming when most projects should make use of it.

As for any specific features of node v4+, just scanning the list on [node.green](https://node.green) makes me realize how frustrating it would be for me to write code without using almost all of the ones that 0.x is missing. Arrow functions & const/let aside, there's native promises, `Object.assign`, `Array.from / of`, `String.startsWith / endsWith / includes`, object literal shorthand... holy crap.

**Comment by szwacz** [comment]
Codebase of this project is in pure ES5 and believe me, I didn't feel like suffering all the time I was writing it ;) Some of the new stuff in ES6 is nice, but this is not a game changer.

I've created new branch for migration to native promises: https://github.com/szwacz/fs-jetpack/tree/native-promises
Please adress all PRs to that branch, not master. I'll start putting some code there as well (but not today yet).

The best approach will be probably to port each method (`copyAsync`, `fileAsync` and so on) in separate PR, until Q can be removed from dependencies.

**Comment by xblox** [comment]
@szwacz give Typescript a try, makes you love Javascript again :-) Btw. It showed a few inconsistencies in your code. I switched to TS because it indeed saves a lot of hassle & time maintaining/extending many packages on the long. However, I can open another issue with the issues I found (minor, but still misleading/confusing)

**Comment by szwacz** [comment]
On branch `native-promises` methods `appendAsync`, `copyAsync`, `dirAsync`, `existsAsync` and `fileAsync` are already migrated to native promises. Migration is fairly simple task and you need just a few minutes for each file. I'll migrate some more tomorrow, or accept any PR doing so ;)

**Comment by szwacz** [comment]
Q has been dropped completely. Thanks for help @citycide!

I have few other things to do before publishig, so the code still isn't in the master barnch.

**Comment by citycide** [comment]
Closing since this was done in [0.13.0](https://github.com/szwacz/fs-jetpack/releases/tag/0.13.0). Reopen if necessary. Thanks :+1:
