### ISSUE TITLE
treeWalkerStream slow

### ISSUE THREAD

**Issue by catx23** [szwacz/fs-jetpack#44]
Hi,
do you have by chance some idea why the treeWalkerStream is around 15 times slower than a native ls -R ?

I was looking at the code and tried a few different flags (times,mode) but no sign of improvements. 

Is it possible that this is caused by using "Readable" ? Because I tested against a trivial implementation for directory (readdirsync) listings and it seems indeed that its of using 'Readable' and events. 

thanks,
g

**Comment by szwacz** [comment]
I'd first compare performance of `walkSync` agains `walkStream`. If walk sync is significantly faster that means performance problem is indeed in streaming itself or doing the streaming inefficiently.

**Comment by xblox** [comment]
ok, that's what i guessed too. 

Just out of curiosity: was there a reason to pipe the listings through a 'Readable' stream? I can imagine to replace this with callbacks just.
g

**Comment by szwacz** [comment]
Stream is async abstraction for exactly what tree walker does: gives you items one by one util all are given. So that's why I used it.

Please tell me how the performance testing of sync vs async walker went.

**Comment by xblox** [comment]
vale, the sync version is almost same fast native for 15k files, nearly 2-3 secs whilst the treeWalkerStream needs around 15 secs on a good SSD rig.

only copy and find is using treewalkerStream whereby both operation are already async and so it should be easy to replace this. gonna try my luck on this today. will let you know.
thanks for the heads up,
g

**Comment by xblox** [comment]
all the other 'walker' implementations from npm are slow too for 15k nodes:

npm module "walkdir" : 4 secs
npm module "walker" : 3.5 secs

treeWalkerStream : 15 secs,
treeWalkerSync: 800ms

I gonna remove treeWalkerStream entirely for treeWalkerSync in **copy** and **find** for my version because I think it's better to work with data determined during a 1 sec window for possible verification later rather than using data collected during that 15 secs. 

gonna close this here, I guess you wanna stick to what's there now in fs-jetpack. 
g

**Comment by szwacz** [comment]
But still the async walker implementation is slower than the competitors. Will look into it in near future (so leave this issue open).

**Comment by xblox** [comment]
oki. I wrapped treewalkerSync in an 'iterator' function [here](https://github.com/xblox/fs/blob/master/src/iterator.ts) and applied it for [copyAsync](https://github.com/xblox/fs/blob/master/src/copy.ts#L590) = all good, tests passed.
g

**Comment by szwacz** [comment]
Solved in v4.1.0
