### ISSUE TITLE
`remove` doesn't handle EBUSY

### ISSUE THREAD

**Issue by citycide** [szwacz/fs-jetpack#47]
This is due to replacing rimraf - which retries on EBUSY, ENOTEMPTY, & EPERM error codes. See here:

https://github.com/isaacs/rimraf/blob/master/rimraf.js#L88-L95

This causes my tests to be really flaky because files won't be removed when I'm expecting them to.

`Error: EBUSY: resource busy or locked, unlink 'C:\Users\...'`

_edit_: accidentally submitted early...

**Comment by szwacz** [comment]
ACK. Tomorrow will have time to look into it.

**Comment by szwacz** [comment]
In version 0.13.3 was able to write one test for such case and fix the code for that test. Please confirm if that fixes the issue for you.

**Comment by xblox** [comment]
@szwacz just out of curiosity, was there a specific reason for replacing _mkdirp_ and _rimraf_ with own code ?

**Comment by szwacz** [comment]
@xblox for few reasons
- to have more code in direct control
- to have as little third party dependencies as possible
- to be able to do fs injection, so you can setup jetpack to use e.g. https://github.com/tschaub/mock-fs instead of standard one (feature I want to implement somewhere in the future)

**Comment by xblox** [comment]
@szwacz thanks for the insights; i'd have prefered fs-jetpack being free of low-level code but ok, fine with me.

**Comment by citycide** [comment]
Yep, checked and it seems 0.13.3 fixed this. Thanks!
