### ISSUE TITLE
dest already exists when copying

### ISSUE THREAD

**Issue by aretecode** [szwacz/fs-jetpack#50]
error is thrown here https://github.com/szwacz/fs-jetpack/blob/master/lib/copy.js#L48

the docs say https://github.com/szwacz/fs-jetpack#copyfrom-to-options
> For directories, source directory is merged with destination directory, so files in destination which are not present in the source, will remain intact.

if I use `overwrite: true`, it will copy, but I don't want it to overwrite - it should just copy.
is this a bug, or intentional? from the docs, I'd think that if I say to copy it over, it adds the files that do not exist in the destination directory.

config used:

```js
const {resolve} = require('path')
const cwd = resolve(__dirname, 'fixtures')
const src = resolve(__dirname, 'fixtures/source')
const dest = resolve(__dirname, 'fixtures/dest')

jetpack.cwd(cwd)
jetpack.copy(entry, dest, {
  matching: ['*.js'],
  overwrite: false,
})
```

fixture used:
<img width="296" alt="screen shot 2017-05-05 at 2 58 21 pm" src="https://cloud.githubusercontent.com/assets/4022631/25765747/63c7655c-31a3-11e7-9cd3-3097991e8d6e.png">

**Comment by szwacz** [comment]
This is intended behaviour. The case you want to achieve indeed might sometimes be useful, but shouldn't happen when overwrite is set to false.

The reasoning:

Let's say we have folders...
```
a
|- foo.html
|- dependency-of-foo.jpg

b
|- foo.html
|- dependecy-of-foo.pdf
```

If by mistake folder `a` would be copied into `b` with proposed by you strategy the outcome is franken-folder of two broken projects.  The files might depend on each other and if you overwrite some of them by mistake you might have a bad evening ;) That's why this is not desired as default action.

The action you want should be possible to achieve by third config state of `overwrite`. I'm thinking about:
```js
{
  overwirite: false,
  overwirite: 'mergeFolders',
  overwirite: true,
}
```
But need to sleep over it. I'm not 100% happy with this API.

Any ideas are welcome.

**Comment by aretecode** [comment]
seems cleaner and simpler with a dedicated property, rather than string values on something currently a boolean.

I would think by default it could also copy all files if there are no conflicting files. in my example, none of the source files exist in the destination.

```js
{
  merge: true,
}
```

**Comment by maca134** [comment]
This feature has broken the example here https://github.com/szwacz/fs-jetpack/blob/master/EXAMPLES.md#3-get-the-job-done-faster-in-your-build-scripts

**Comment by szwacz** [comment]
@maca134 This is not implemented yet, so it didn't broke the example. The example was broken because I've actually never run that code, just wrote it once from the top of my head ;)

**Comment by aretecode** [comment]
@szwacz 💡 idea on this: allow a callback for `overwrite`, or add `.onConflict`

**Comment by szwacz** [comment]
Yes! Function passed to `overwrite` param is the most pretty and elastic solution. Will try to find time next week to work on it.

**Comment by aretecode** [comment]
@szwacz any luck on this?

**Comment by szwacz** [comment]
Hey.

I was tinkering with it myself, but stumbled upon few issues and needed someone to push on my motivation ;).

Thanks for the PR! But this function stuff can do much more (e.g. overwirite only if file newer) and for that inspect of both files is necessary (and that's where I stumbled upon performance problems). I'd like to extend your work, and published special branch for that purpose: `copy-overwrite`, please make the PR against that branch and I'll add my ideas.

**Comment by aretecode** [comment]
@szwacz done, yes I've done similar things for specifications on the file stats, however, if you have the absolute path, then you can use any of the other fs-jetpack functions to help assist make those specifications. Once people have made some specifications, you'll know which ones would be helpful, and not YAGNI

**Comment by szwacz** [comment]
Well if you want to just have the feature then yes, if you want to have the feature in performant and ellegant way this is not that simple.

1. The function which decides what to overwrite expects synchronous return, so if you want to do purely async copying you're screwed (can't call async inspect inside).
2. In your implementation the function is called for every copied item, since this is overwrite feature the desired behaviour is to call it only for real cases of file conflicts.

Will tinker with it on the weekend. Stay tuned.

**Comment by szwacz** [comment]
Done! Version 1.1.0 has this feature, please give it a shot. I've changed the function schema to only have two inspect objects with many properties inside (inside the object there is a path to file as well).
