### ISSUE TITLE
option to use `trash` instead of forever delete

### ISSUE THREAD

**Issue by aretecode** [szwacz/fs-jetpack#54]
https://github.com/sindresorhus/trash
so that deletion can be undone

**Comment by szwacz** [comment]
Thanks for suggesting. Unfortunately I don't think there is a sensible way of adding this functionality to fs-jetpack. Trash library uses [operating systems API magic](https://github.com/sindresorhus/trash/tree/master/lib) to achieve its goal, and I'd rather send people to that library instead of trying to reimplement the same stuff in fs-jetpack.
