### ISSUE TITLE
Default .copy overwrite would be welcome

### ISSUE THREAD

**Issue by mwpowellhtx** [szwacz/fs-jetpack#62]
When  I file is copying for the first time, i.e. does not exist in the destination, it would be great if a default ``overwrite`` were to be provided.

Assuming ``opts`` is passed to ``.copy``, i.e. as follows:

```JavaScript
opts.overwrite = () => true;
```

It is easy enough for me to provide one, but as a matter of doing business, especially after I've checked for existence of the destination, I do not expect to have to provide a default callback.

**Comment by szwacz** [comment]
I don't quite get your use case. Can you elaborate a bit more? If the file doesn't exist in destination why would overwrite even apply? :)

**Comment by mwpowellhtx** [comment]
@szwacz i.e. ``.copy(..., { overwrite: () => true })``

**Comment by szwacz** [comment]
Well, there is default overwrite, and the value is `false` :) This is because by default we want to be safe. Overwriting means some data will be lost, and therefore should be performed only if explicitly configured this way.

**Comment by mwpowellhtx** [comment]
@szwacz I beg to differ on that. I received an error/exception when I did not provide one.

**Comment by szwacz** [comment]
Do you have a code snippet to reproduce the error?

**Comment by mwpowellhtx** [comment]
@szwacz The path does not exist, yet. I created the directory and initialized my Git repository there. Then I attempt to copy, and receive this error:

```JavaScript
var fs = require("fs-jetpack");
// ...
var copyOpts = { matching: tarballName };
// ...
fs.copy(srcDir, repoDir, copyOpts);
```

Like I said, the file does not exist yet, the copy should just work.

My dependency:

```JavaScript
devDependencies: {
    // ...
    "fs-jetpack": "1.2.0",
    // ...
}
```

```
G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Working\src\ExtensionsJS.Array\node_modules\fs-jetpack\lib\copy.js:75
    throw generateDestinationExistsError(to);
    ^
Error: Destination path already exists G:\Source\Kingdom Software\JavaScript\Node.js\Registries\extensionsjs-array2
    at generateDestinationExistsError (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Working\src\ExtensionsJS.Array\node_modules\fs-jetpack\lib\copy.js:49:15)
    at checksBeforeCopyingSync (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Working\src\ExtensionsJS.Array\node_modules\fs-jetpack\lib\copy.js:75:11)
    at Object.copySync [as sync] (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Working\src\ExtensionsJS.Array\node_modules\fs-jetpack\lib\copy.js:138:3)
    at Object.copy (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Working\src\ExtensionsJS.Array\node_modules\fs-jetpack\lib\jetpack.js:78:12)
    at doPublish (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Working\src\ExtensionsJS.Array\Gulpfile.js:188:20)
    at git.init.err (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Working\src\ExtensionsJS.Array\Gulpfile.js:207:21)
    at Git.<anonymous> (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Working\src\ExtensionsJS.Array\node_modules\simple-git\src\git.js:137:18)
    at done (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Working\src\ExtensionsJS.Array\node_modules\simple-git\src\git.js:1354:21)
    at ChildProcess.<anonymous> (G:\Source\Kingdom Software\JavaScript\ExtensionsJS\Working\src\ExtensionsJS.Array\node_modules\simple-git\src\git.js:1379:16)
    at emitTwo (events.js:126:13)
Process terminated with code 1.
```

**Comment by mwpowellhtx** [comment]
@szwacz There does appear to be a latest version ``1.3.0``. Possibly this was a patch in that package?

**Comment by mwpowellhtx** [comment]
@szwacz If I add the following line, then the operation "works", but I contend it shouldn't really be necessary.

```JavaScript
copyOpts.overwrite = () => true;
fs.copy(srcDir, repoDir, copyOpts);
```

**Comment by szwacz** [comment]
Ok, so you have the destination directory existing, but it's empty. Technically speaking you're overwriting empty folder with folder with data, so this is still overwriting. Not overwriting is only when destination path doesn't exits. I don't think I can help here.

**Comment by mwpowellhtx** [comment]
@szwacz I'm not sure I follow. The ``matching`` criteria does not narrow the operation to the *file(s)* matching the criteria?

**Comment by mwpowellhtx** [comment]
@szwacz Or perhaps to frame the question differently. Can I specify a *file* path and not a directory to ``.copy`` instead? That would be more precise anyway, but the examples I've seen are of a directory with ``matching`` criteria, which, when push comes to shove, is a bit imprecise when it comes to applying consistent operations such as ``.overwrite``.

**Comment by szwacz** [comment]
To determine if overwrite can happen the code is checking if destination path exists. If source path is a folder, and destination path is a folder, then even if the dest folder is empty technically speaking the folder has been overwritten (actually two folders merged together). I used this behaviour because this is how the problem is solved by default file managers in operating systems, so people are familiar with the concept. 

Specifying `matching` option doesn't alter this behaviour and I'm not sure it should, because then the configuration rules are getting more complex.

BTW, this is tricky subject, because folders and files are not the same enough to treat them as the same, and at the same time on given path you may have one or the other and you don't know until you check.

When I was designing this API, I was thinking for a while about two options: `merge` and `overwrite`. Because this is what you really do to folders - merging them, not necessarily overwriting anything inside. But this solution had it's own problems so I've finally ditched it.

**Comment by szwacz** [comment]
To recap.

Even when you merge two folders together, but without overwriting any file inside destination folder. And you did the merge by mistake. You created a mess, which you can undo, but effort need to be put into the situation.

Better to be safe than sorry, that's why by default fs-jetpack doesn't merge/overwrite anything, until explicitly told to.

**Comment by mwpowellhtx** [comment]
@szwacz Let me see if I understand you then. *"If source path is a folder..."*, am I understanding correctly, that *files* may be specified as *source*? Possibly also *destination* (i.e. copy, but rename as it does)? That would work best, I think, but I just wanted to clarify. I could still provide an ``overwrite`` callback with more specifics in mind to be sure.
